version: 2
registries:
  ghpr:
    type: docker-registry
    url: docker.pkg.github.com
    username: x
    password: ${{ secrets.DEPENDABOT_GHPR_TOKEN }}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directory: '/docker'
    schedule:
      interval: 'daily'
    registries:
      - ghpr
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

