name: 'integration'

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

permissions:
  contents: read
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: GPR login
        run: docker login docker.pkg.github.com -u x -p ${{ secrets.GITHUB_TOKEN }}
      - name: GRP pull dependabot/dependabot-updater
        run: docker pull docker.pkg.github.com/dependabot/dependabot-updater:latest
      - name: GRP pull github/dependabot-update-job-proxy
        run: docker pull docker.pkg.github.com/github/dependabot-update-job-proxy:latest
      - run: npm ci
      - name: Run integration test files
        run: npm run test-integration
